name: t_teet_rider
description: Rider application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6
  cloud_firestore: ^0.12.9+5
  firebase_messaging: ^6.0.16

  flutter_local_notifications: ^1.4.4+2
  http: ^0.12.2
  gender_selection: ^1.0.0
  shared_preferences: ^0.5.8
  simple_animations: ^2.2.1
  image_picker: ^0.6.7+4
  nepali_date_picker: ^4.1.0
  flutter_offline: ^0.3.0
  cached_network_image: ^2.2.0+1
  carousel_slider: ^2.2.1
  bubble_tab_indicator: ^0.1.4
  percent_indicator: ^2.1.5
  google_maps_flutter: ^0.5.21+15
  location: ^3.0.0
  lite_rolling_switch: ^0.1.1
  flutter_rating_bar: ^3.0.1+1
  overlay_support: ^1.0.0
  bubble: ^1.1.9+1

  flutter_styled_toast: ^1.3.2
  pin_code_fields: ^4.0.0
  otp_text_field: ^1.0.1
  provider: ^4.3.2
  persistent_bottom_nav_bar: ^2.0.5
  connectivity: ^0.4.9+2
  flutter_keyboard_visibility: ^3.2.2
  firebase_database: ^3.1.6
  rxdart: ^0.24.1
  flutter_polyline_points: ^0.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/started.jpg
    - assets/images/test.jpg
    - assets/images/bike.png
    - assets/images/vechile.png
    - assets/images/lic.png
    - assets/images/doccc.png
    - assets/images/home2.png
    - assets/images/stering.png
    - assets/images/reward.png
    - assets/images/summary.png
    - assets/images/db.png
    - assets/images/refreshClock.PNG
    - assets/images/learn.png
    - assets/images/multipleDoc.png
    - assets/images/help.png
    - assets/images/document.png
    - assets/images/history.png
    - assets/images/gold.png
    - assets/images/silver.png
    - assets/images/nepal_flag.png
    - assets/images/filtering.png
    - assets/images/location.png
    - assets/images/customMenu.png
    - assets/images/help1.png
    - assets/images/help2.png
    - assets/images/driverDoc.PNG
    - assets/images/highAlert.PNG
    - assets/images/updateProfile.PNG
    - assets/images/logowithguru.PNG
    - assets/images/genderMale.PNG
    - assets/images/genderFemale.PNG
    - assets/images/cameraIcon.PNG
    - assets/images/learningCenterBanner.PNG
    - assets/images/shieldUser.png
    - assets/images/dollarSign1.PNG
    - assets/images/starRating.png
    - assets/images/vehicle1.png
    - assets/images/carRent.png
    - assets/images/maleMarker.png
    - assets/images/femaleMarker.png
    - assets/images/male.png
    - assets/images/female.png
  fonts:
    - family: gothamBook
      fonts:
        - asset: assets/font/HomepageBaukasten-Book.ttf
    - family: gothamRegular
      fonts:
        - asset: assets/font/Gotham-Medium.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
#  - asset: assets/font/HomepageBaukasten-Book.ttf
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:



  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
